[package]
name = "thanatos-module"
version = "0.1.0"
edition = "2021"

[dependencies.thanatos-module-macros]
optional = true
path = "thanatos-module_macros"
default-features = false

[features]
default = ["std"]
macros = ["thanatos-module-macros"]
std = ["thanatos-module-macros/std"]
