[package]
name = "thanatos_library"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies.thanatos_core]
path = "../core"
