[package]
name = "thanatos_http_cdylib"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
thanatos_http = { path = ".." }
