[package]
name = "commands-pwd"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies.thanatos-module]
optional = true
path = "../../thanatos-module"
features = ["macros"]

[features]
load = ["dep:thanatos-module"]
