[package]
name = "config"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true

[lints]
workspace = true

[features]

[dependencies]
rmp = "0.8.12"
rmp-serde = "1.1.2"
serde.workspace = true
serde_repr = "0.1"

[dependencies.utils]
path = "../utils"

[build-dependencies]
base64 = "0.21.5"
rmp = "0.8.12"
rmp-serde = "1.1.2"
serde.workspace = true
serde_json = "1"
serde_repr = "0.1"
utils = { path = "../utils" }
sha2 = "0.10.8"
