[package]
name = "config"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true

[lints]
workspace = true

[features]

[dependencies]
rmp = "0.8.12"
rmp-serde = "1.1.2"
serde = { version = "1", features = ["derive"] }

[build-dependencies]
rmp = "0.8.12"
rmp-serde = "1.1.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.21.5"
