[build]
rustc-wrapper = "/usr/bin/sccache"

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
