[package]
name = "utils"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true


[dependencies]
serde.workspace = true

[lints]
workspace = true
