[package]
name = "thanatos-bin"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[features]
daemonize = []
eke = []
tlsuntrusted = []
systemproxy = []

[dependencies]
thanatos = { path = ".." }
