name: Setup lint environment
description: Sets up an environment for running checks
inputs:
  agent-code:
    description: Path to the agent code
    required: true

  mythic-code:
    description: Path to the Mythic code

runs:
  using: "composite"
  steps:
    - name: Install Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install Golang modules
      shell: bash
      working-directory: ${{ inputs.mythic-code }}
      run: go mod download

    - name: Setup cargo cache
      uses: actions/cache@v4
      working-directory: ${{ inputs.agent-code }}
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          ${{ runner.os }}-cargo

    - name: Setup cargo target cache
      uses: actions/cache@v4
      working-directory: ${{ inputs.agent-code }}
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          ${{ runner.os }}-cargo-target
