name: Setup lint environment
description: Sets up an environment for running various checks
inputs:
  mythic-code:
    description: Path to the mythic code
    required: true

  agent-code:
    description: Path to the agent code
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      shell: bash
      run: pipx install poetry

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "poetry"

    - name: Install Python packages
      shell: bash
      run: poetry install -C ${{ inputs.mythic-code }}

    - name: Setup cargo cache
      uses: actions/cache@v4
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles(format('{0}/Cargo.toml', inputs.agent-code)) }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles(format('{0}/Cargo.toml', inputs.agent-code)) }}
          ${{ runner.os }}-cargo

    - name: Setup cargo target cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.AGENT_CODE }}/target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles(format('{0}/Cargo.toml', inputs.agent-code)) }}
        restore-keys: |
          ${{ runner.os }}-cargo-target-${{ hashFiles(format('{0}/Cargo.toml', inputs.agent-code)) }}
          ${{ runner.os }}-cargo-target
