[package]
name = "errors"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true


[dependencies]

[target.'cfg(target_os = "windows")'.dependencies]
windows.workspace = true

[dependencies.ffiwrappers]
path = "../ffiwrappers"
