name: Setup lint environment
description: Sets up an environment for running checks
inputs:
  agent-code:
    description: Path to the agent code
    required: true

  mythic-code:
    description: Path to the Mythic code

runs:
  using: "composite"
  steps:
    - name: Install Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install Golang modules
      shell: bash
      run: cd ${MYTHIC_CODE} && go mod download
      env:
        MYTHIC_CODE: ${{ inputs.mythic-code }}

    - name: Setup cargo cache
      uses: actions/cache@v4
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles(format('{0}/Cargo.toml', inputs.agent-code)) }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles(format('{0}/Cargo.toml', inputs.agent-code)) }}
          ${{ runner.os }}-cargo

    - name: Setup cargo target cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.AGENT_CODE }}/target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles(format('{0}/Cargo.toml', inputs.agent-code)) }}
        restore-keys: |
          ${{ runner.os }}-cargo-target-${{ hashFiles(format('{0}/Cargo.toml', inputs.agent-code)) }}
          ${{ runner.os }}-cargo-target
