##### WORKSPACE DEFINITION #####
[workspace]
resolver = "2"
members = [
  "config",
  "ffiwrappers",
  "thanatos",
  "thanatos/cdylib",
  "thanatos/binary",
  "utils",
  "cryptolib",
  "errors",
  "genconfig",
  "profiles/http", "profiles/base",
]

default-members = ["thanatos"]

exclude = ["shellcode-builder"]

[workspace.package]
authors = ["@M_alphaaa"]
edition = "2021"
homepage = "https://github.com/MythicAgents/thanatos"
license = "BSD-3-Clause"
version = "0.2.0"


##### WORKSPACE DEPENDENCIES #####
[workspace.dependencies]
base64 = "0.22.0"
cfg-if = "1"
chrono = "0.4.34"
hex-literal = "0.4.1"
prost = "0.12"
prost-types = "0.12"
prost-build = "0.12"
serde_json = "1"
sha2 = "0.10.8"
bitflags = "2.4.2"

[workspace.dependencies.libc]
version = "0.2"

[workspace.dependencies.rand]
version = "0.8.5"
default-features = false
features = ["std_rng", "small_rng", "getrandom"]

[workspace.dependencies.serde]
version = "1"
features = ["derive"]

[workspace.dependencies.windows]
version = "0.54.0"
features = [
  "Win32_Foundation",
  "Win32_System",
  "Win32_System_SystemInformation",
  "Win32_Security_Cryptography",
  "Win32_System_WindowsProgramming",
  "Win32_System_LibraryLoader",
  "Win32_System_Threading",
  "Win32_System_SystemServices",
  "Wdk",
  "Wdk_System",
  "Wdk_System_SystemServices",
  "Wdk_System_SystemInformation",
]

##### WORKSPACE SETTINGS #####

##### BUILD SETTINGS #####
[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = 'z'
