##### MAIN PACKAGE DEFINITION #####
[package]
name = "thanatos"
version = "2.0.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true

[lib]
name = "thanatos_core"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "thanatos"
path = "src/main.rs"

[dependencies.config]
path = "./config"

[features]
init-thread = []
init-daemonize = []

##### WORKSPACE DEFINITION #####
[workspace]
members = ["config"]

[workspace.package]
authors = ["@M_alphaaa"]
edition = "2021"
homepage = "https://github.com/MythicAgents/thanatos"
license = "BSD-3-Clause"


##### WORKSPACE DEPENDENCIES #####


##### WORKSPACE SETTINGS #####
[workspace.lints.rust]
elided_lifetimes_in_paths = "warn"
explicit_outlives_requirements = "warn"
keyword_idents = "deny"
macro_use_extern_crate = "deny"
missing_docs = "warn"
non_ascii_idents = "deny"
pointer_structural_match = "deny"
single_use_lifetimes = "warn"
unreachable_pub = "warn"
unsafe_op_in_unsafe_fn = "deny"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"
unused_qualifications = "warn"
unused_tuple_struct_fields = "warn"
variant_size_differences = "warn"

##### BUILD SETTINGS #####
[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip = true
opt-level = 'z'
