###### WORKSPACE ITEMS ######
[workspace]
members = [
  "agent",
  "agent_utils",
  "commands/pwd",
  "commands/cat",
  "commands/cd",
  "config",
  "profiles/egress",
  "profiles/p2p",
  "thanatos-module"
]

default-members = ["agent", "agent_utils", "config"]
exclude = [
  "thanatos-module/loadapi_macros",
]


###### WORKSPACE DEPENDENCIES ######
[workspace.dependencies]
serde_json = "1.0"


[workspace.dependencies.base64]
version = "0.21"
default-features = false
features = ["alloc"]

[workspace.dependencies.libc]
version = "0.2"
features = ["extra_traits"]

[workspace.dependencies.openssl]
version = "0.10.46"
features = ["vendored"]

[workspace.dependencies.rand]
version = "0.8.5"
default-features = false
features = ["alloc", "small_rng", "getrandom"]

[workspace.dependencies.serde]
version = "1.0"
features = ["derive"]

[workspace.dependencies.windows]
version = "0.48"
default-features = false
features = [
  "Win32_Foundation",
  "Win32_System_SystemInformation",
  "Win32_Networking_WinHttp",
  "Win32_System_LibraryLoader",
  "Win32_System_Threading",
  "Win32_Security",
  "Win32_System_WindowsProgramming",
  "Win32_NetworkManagement_IpHelper",
  "Win32_Security_Cryptography"
]


###### BUILD SETTINGS ######
[profile.dev.package.num-bigint-dig]
opt-level = 3 # ref: https://github.com/RustCrypto/RSA#example

[profile.release]
strip = true
lto = true
codegen-units = 256
opt-level = 3
panic = "abort"
