##### WORKSPACE DEFINITION #####
[workspace]
resolver = "2"
members = [
  "config",
  "ffiwrappers",
  "thanatos_bin",
  "thanatos_core",
  "thanatos_lib",
  "utils",
]

default-members = ["thanatos_core"]

exclude = [
  "shellcode-builder"
]

[workspace.package]
authors = ["@M_alphaaa"]
edition = "2021"
homepage = "https://github.com/MythicAgents/thanatos"
license = "BSD-3-Clause"


##### WORKSPACE DEPENDENCIES #####
[workspace.dependencies]

[workspace.dependencies.serde]
version = "1"
features = ["derive"]

##### WORKSPACE SETTINGS #####
[workspace.lints.rust]
elided_lifetimes_in_paths = "warn"
explicit_outlives_requirements = "warn"
keyword_idents = "deny"
macro_use_extern_crate = "deny"
missing_docs = "warn"
non_ascii_idents = "deny"
pointer_structural_match = "deny"
single_use_lifetimes = "warn"
unreachable_pub = "warn"
unsafe_op_in_unsafe_fn = "deny"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"
unused_qualifications = "warn"
unused_tuple_struct_fields = "warn"
variant_size_differences = "warn"

##### BUILD SETTINGS #####
[profile.release]
lto = true
codegen-units = 256
panic = 'abort'
strip = true
opt-level = 'z'
