##### WORKSPACE DEFINITION #####
[workspace]
resolver = "2"
members = [
  "config",
  "ffiwrappers",
  "thanatos_agent",
  "thanatos_agent/cdylib",
  "thanatos_agent/binary",
  "utils",
  "cryptolib",
  "errors",
  "genconfig",
]

default-members = ["thanatos_agent"]

exclude = ["shellcode-builder"]

[workspace.package]
authors = ["@M_alphaaa"]
edition = "2021"
homepage = "https://github.com/MythicAgents/thanatos"
license = "BSD-3-Clause"
version = "0.2.0"


##### WORKSPACE DEPENDENCIES #####
[workspace.dependencies]
base64 = "0.21.5"
cfg-if = "1"
chrono = "0.4.34"
hex-literal = "0.4.1"
quick-protobuf = "0.8.1"
serde_json = "1"
sha2 = "0.10.8"
bitflags = "2.4.2"

[workspace.dependencies.dbus]
version = "0.9.7"
default-features = false

[workspace.dependencies.libc]
version = "0.2"

[workspace.dependencies.pb-rs]
version = "0.10.0"
default-features = false

[workspace.dependencies.serde]
version = "1"
features = ["derive"]

[workspace.dependencies.windows]
version = "0.52.0"
features = [
  "Win32_Foundation",
  "Win32_System",
  "Win32_System_SystemInformation",
  "Win32_Security_Cryptography",
  "Win32_System_WindowsProgramming",
]

##### WORKSPACE SETTINGS #####

##### BUILD SETTINGS #####
[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = 'z'
