##### WORKSPACE DEFINITION #####
[workspace]
resolver = "2"
members = [
  "config",
  "ffiwrappers",
  "genconfig",
  "thanatos_core",
  "thanatos_http",
  "thanatos_http/cdylib",
  "thanatos_http/binary",
  "utils",
]

default-members = ["thanatos_core"]

exclude = [
  "shellcode-builder",
]

[workspace.package]
authors = ["@M_alphaaa"]
edition = "2021"
homepage = "https://github.com/MythicAgents/thanatos"
license = "BSD-3-Clause"
version = "0.2.0"


##### WORKSPACE DEPENDENCIES #####
[workspace.dependencies]
base64 = "0.21.5"
rmp = "0.8.12"
rmp-serde = "1.1.2"
serde_json = "1"
serde_repr = "0.1"
serde_bytes = "0.11"
sha2 = "0.10.8"

[workspace.dependencies.serde]
version = "1"
features = ["derive"]

##### WORKSPACE SETTINGS #####

##### BUILD SETTINGS #####
[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = 'z'
