[package]
name = "thanatos-module-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies.syn]
version = "2.0.2"
features = ["full", "extra-traits", "parsing"]

[features]
std = []
