[package]
name = "base-profile"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true


[dependencies]
prost.workspace = true

[build-dependencies]
prost-build.workspace = true
