[package]
name = "thanatos_lib"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true

[lib]
name = "thanatos"
crate-type = ["cdylib"]

[dependencies]
thanatos_core = { path = "../thanatos_core" }

[lints]
workspace = true
