name: Build and push the base container image
description: Builds and pushes the base container image for Thanatos

inputs:
  image-registry:
    description: Registry to push the image to
    required: true
    default: ghcr.io

  image-name:
    description: Name of the container image
    required: true

  image-tag:
    description: Tag to add to the container image
    required: true

  image-description:
    description: Description for the container in the package view
    required: true

  image-license:
    description: License to add to the container image
    required: true

  github-token:
    required: true


runs:
  using: "composite"
  steps:
    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.image-registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Set the container image fully qualified url
      shell: bash
      run: echo "IMAGE_URL=${IMAGE_URL,,}" >> ${GITHUB_ENV}
      env:
        IMAGE_URL: ${{ inputs.image-registry }}/${{ inputs.image-name }}:${{ inputs.image-tag }}

    - name: Build and push the container image
      uses: docker/build-push-action@v5
      with:
        context: Payload_Type/thanatos
        file: Payload_Type/thanatos/.docker/Dockerfile
        tags: ${{ env.IMAGE_URL }}
        push: true
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.description=${{ inputs.image-description }}
          org.opencontainers.image.licenses=${{ inputs.image-license }}
