name: "Install dependencies"
description: "Setup dependencies for workflows"

runs:
  using: "composite"

  steps:
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version-file: Payload_Type/thanatos/mythic/go.mod
        cache-dependency-path: Payload_Type/thanatos/mythic/go.sum

    - name: Setup Linux dependencies
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          make \
          curl \
          lcov

        go install golang.org/x/tools/cmd/cover@latest
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

        curl \
          -L https://github.com/protocolbuffers/protobuf/releases/download/v27.3/protoc-27.3-linux-x86_64.zip \
          -o /tmp/protoc.zip
        sudo unzip /tmp/protoc.zip -x readme.txt -d /usr/local
        rm -rf /tmp/protoc.zip

        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s - -y --profile minimal -c clippy llvm-tools-preview
        . "$HOME/.cargo/env"
        rustup toolchain install nightly
        rustup component add rust-src --toolchain nightly
        curl \
          -L https://github.com/mozilla/grcov/releases/download/v0.8.19/grcov-x86_64-unknown-linux-gnu.tar.bz2 \
          -o /tmp/grcov.tar.bz2
        sudo tar xvf /tmp/grcov.tar.bz2 -C /usr/local/bin
        rm -rf /tmp/grcov.tar.bz2

    - name: Setup Windows dependencies
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        Invoke-WebRequest `
          -Uri https://github.com/protocolbuffers/protobuf/releases/download/v25.3/protoc-25.3-win64.zip `
          -OutFile $env:TEMP\protoc.zip

        Expand-Archive $env:TEMP\protoc.zip
        Copy-Item -Path $env:TEMP\protoc\bin\protoc.exe -Destination $env:SYSTEMROOT\System32\protoc.exe
        Remove-Item -Recurse $env:TEMP\protoc
        Remove-Item $env:TEMP\protoc.zip

        Invoke-WebRequest `
          -Uri https://github.com/mozilla/grcov/releases/download/v0.8.19/grcov-x86_64-pc-windows-msvc.zip `
          -OutFile $env:TEMP\grcov.zip

        Expand-Archive $env:TEMP\grcov.zip
        Copy-Item -Path $env:TEMP\grcov\grcov.exe -Destination $env:SYSTEMROOT\System32\grcov.exe
        Remove-Item -Recurse $env:TEMP\grcov
        Remove-Item $env:TEMP\grcov.zip

        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        rustup component add llvm-tools-preview
        rustup toolchain install nightly
        rustup component add rust-src --toolchain nightly
