name: Debug Workflow

on:
  push:
    branches:
      - rewrite

jobs:
  debug:
    runs-on: windows-latest

    steps:
      - name: Enter VS shell print env
        run: |
          $vspath = (Get-VSSetupInstance | Select-VSSetupInstance -Require Microsoft.VisualStudio.Component.VC.ASAN).InstallationPath
          Import-Module $vspath/Common7/Tools/Microsoft.VisualStudio.DevShell.dll
          Enter-VsDevShell -VsInstallPath $vspath -SkipAutomaticLocation
          ls env:
