name: Debug Workflow

on:
  push:
    branches:
      - rewrite

jobs:
  debug:
    runs-on: windows-latest

    steps:
      - name: Get VS Install path
        run: Write-Host (Get-VSSetupInstance | Select-VSSetupInstance -Require Microsoft.VisualStudio.Component.VC.ASAN).InstallationPath
