name: Development CI

on:
  push:
    branches:
      - rewrite
      - test/**

    paths:
      - Payload_Type/thanatos/agent/**
      - Payload_Type/thanatos/mythic/**
      - .github/workflows/**
      - .github/actions/**

  pull_request:
    types:
      - opened
    branches:
      - rewrite
    paths:
      - Payload_Type/thanatos/agent/**
      - Payload_Type/thanatos/mythic/**
      - .github/workflows/**
      - .github/actions/**

env:
  AGENT_CODE: Payload_Type/thanatos/agent
  MYTHIC_CODE: Payload_Type/thanatos/mythic

jobs:
  lint-workflow:
    name: Lint
    uses: ./.github/workflows/lint.yml

  test-workflow:
    name: Test
    uses: ./.github/workflows/test.yml
