name: Development CI

on:
  push:
    branches:
      - rewrite

    paths:
      - Payload_Type/thanatos/**
      - .github/workflows/**
      - .github/actions/**

  pull_request:
    types:
      - opened
    branches:
      - rewrite
    paths:
      - Payload_Type/thanatos/**

jobs:
  lint-workflow:
    name: Lint
    uses: ./.github/workflows/lint.yml

  test-workflow:
    name: Test
    uses: ./.github/workflows/test.yml
