name: Run tests

on:
  workflow_call:

env:
  AGENT_CODE: Payload_Type/thanatos/agent
  MYTHIC_CODE: Payload_Type/thanatos/mythic


jobs:
  agent:
    name: Agent Tests

    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.platform.os }}

    defaults:
      run:
        working-directory: ${{ env.AGENT_CODE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system libraries
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update -y && sudo apt-get install -y libdbus-1-dev

      - name: Run tests
        run: cargo test --color always --workspace --exclude genconfig --all-features --target ${{ matrix.platform.target }}

  mythic:
    name: Mythic Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.MYTHIC_CODE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Golang modules
        run: go mod download

      - name: Command tests
        run: go test ./commands/...

      - name: Mockbuild tests
        run: go test -run "^TestPayloadMockBuild/" ./builder
