name: Run tests

on:
  workflow_call:

env:
  AGENT_CODE: Payload_Type/thanatos/agent
  MYTHIC_CODE: Payload_Type/thanatos/mythic


jobs:
  agent:
    name: Agent Tests

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ${{ env.AGENT_CODE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup cargo cache
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles(format('{0}/Cargo.lock', env.AGENT_CODE)) }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles(format('{0}/Cargo.lock', env.AGENT_CODE)) }}
            ${{ runner.os }}-cargo

      - name: Setup cargo target cache
        uses: actions/cache@v4
        with:
          path: ${{ env.AGENT_CODE }}/target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles(format('{0}/Cargo.lock', env.AGENT_CODE)) }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ hashFiles(format('{0}/Cargo.lock', env.AGENT_CODE)) }}
            ${{ runner.os }}-cargo-target

      - name: Install system libraries
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update -y && sudo apt-get install -y libdbus-1-dev

      - name: Run tests
        run: |
          cargo build -p genconfig
          cargo test --color always --workspace --exclude genconfig --all-features

  mythic:
    name: Mythic Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.MYTHIC_CODE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.MYTHIC_CODE }}/go.mod
          cache-dependency-path: ${{ env.MYTHIC_CODE }}/go.sum

      - name: Install Golang modules
        run: go mod download

      - name: Command tests
        run: go test ./commands/...

      - name: Mockbuild tests
        run: go test -run "^TestPayloadMockBuild/" ./builder
